
name: Deploy Docs

on:
  push:
    branches:
      # make sure this is the branch you are using
      - main

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Install Deps
        run: npm ci

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
